### ISSUE TITLE
Support for external TSDB storage

### ISSUE THREAD

**Issue by weeco** [nakabonne/tstorage#32]
Hey,
I'd like to use tstorage but I'd like to use an external persistence (in my case Kafka). Do you think this would make sense to support so that we can use external systems like Databases or even streams like Kafka for the persistence?

My usecase is to utilize tstorage to collect some metrics for [Kowl](https://github.com/cloudhut/kowl) so that we can show some graphs (e.g. storage usage over time). Ideally we don't need our users to configure a filestorage, but instead we could use something like a Kafka topic that can be shared by all instances.

**Comment by nakabonne** [comment]
Cool! I hope it will work as well as we'd like. Please report if you face any kind of issues and ask me anything ;)

For now let me close this issue but feel free to comment and open it if needed.

**Comment by nakabonne** [comment]
@weeco Out of curiosity, I found out the commit that sets the retention to `tstorage`: https://github.com/cloudhut/kowl/commit/6bc01395aa04f37c6f45c4e9eaa588b3771476c3

Looks like you set the retention with `WithPartitionDuration`. Sorry for confusing you but actually it has no sense in the in-memory mode because that option specifies just when to remove old data from the disk.

Instead, it may work as well as you'd like:

```go
	tsdbOpts := []tstorage.Option{
		tstorage.WithTimestampPrecision(tstorage.Seconds),
		tstorage.WithPartitionDuration(cfg.Retention/2)
	}
```

`tstorage` internally has a tiny completely independent database called Partition. Only the two most recent partitions are cached in memory, so by setting the duration of a partition to half of the retention you'd like, you can cache data points in memory for the duration of the retention you'd like.
See: https://github.com/nakabonne/tstorage/blob/main/README.md#memory-partition

I hope it helps you.

**Comment by nakabonne** [comment]
@weeco [v0.3.0](https://github.com/nakabonne/tstorage/releases/tag/v0.3.0) that comes with WAL support is out just now! It's enabled by default in the on-disk mode. So it may be helpful to bump `tstorage` to this version.
